version: "3.5"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.localhost"
      - "traefik.port=9000"
    restart: always
    privileged: true
    depends_on:
      - traefik
    networks:
      - traefik_webgateway

  traefik:
    image: traefik:latest
    container_name: traefik
    command: --api --docker --logLevel=DEBUG --docker.exposedByDefault=false --docker.domain=localhost
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.localhost"
      - "traefik.port=8080"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - webgateway

volumes:
  data:
    name: portainer_data

networks:
  traefik_webgateway:
    external:
      name: traefik_webgateway
  webgateway:
    driver: bridge
    name: traefik_webgateway
